### ISSUE TITLE
Long Bytes Send

### ISSUE THREAD

**Issue by Jatindersyall12** [dariuszseweryn/RxAndroidBle#837]
Hello

I am not able to send long bytes please help me. I wants to send 10k character.
Thanks

**Comment by dariuszseweryn** [comment]
Hello,
Your post lacks actionable information. I cannot help you unless you will provide more information. 
What you have tried till now? What the peripheral you communicate with expects? Is there any encoding involved? Is there any ACK signal from the peripheral?

**Comment by Jatindersyall12** [comment]
Hey @dariuszseweryn 

I am using your's **LongWriteExampleActivity** and try to send the large data in two devices. I am passing static DUMMY_DEVICE_ADDRESS of other android device.

Can you tell me the steps if I am following wrong.

**Comment by dariuszseweryn** [comment]
> Can you tell me the steps if I am following wrong

TBH, I cannot. You did not provided any steps you took apart of (what I interpret as) setting peripheral's device address.
There is no info about if there is a BLE server running on the peripheral nor if there are any services/characteristics specified. `LongWriteExampleActivity` has some assumptions as it is described in the Javadoc.

**Comment by dariuszseweryn** [comment]
[There are two classes named like that in this repository](https://github.com/search?q=repo%3Adariuszseweryn%2FRxAndroidBle%20LongWriteExampleActivity&type=code). I don't know which sample app you used.

**Comment by Jatindersyall12** [comment]
@dariuszseweryn Yes I am using this class. Can you tell me what I need to do to use this class. I am directly open this class from mainfest when my app loads.

Can you tell me from where I can call this class to see working code ?

What I need to replace under my DUMMY_DEVICE_ADDRESS?. Right Now I am placing the address of another android phone.

**Comment by dariuszseweryn** [comment]
I believe there are comments and Javadocs in related classes — no?

I cannot tell you what exactly needs to be done since you have not provided any information about the server implementation. 

High level description of what you need is that you create BluetoothGattServer that will be your peripheral. On the server you need to declare characteristics that will receive the data. Then you need to scan the server and send the data to declared characteristic. Depending on the server implementation you will need to use ACK notifications or not.

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
